[package]
name = "fensor"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "A filesystem-backed Tensor with dense and sparse indexing"
repository = "https://github.com/TinyChain-Inc/fensor"

[dependencies]
b-table = { path = "../b-table", features = ["stream"] }
destream = "0.10"
freqfs = "0.12"
ha-ndarray = "0.5"
futures = "0.3"
rand = "0.8"
safecast = "0.2"
smallvec = "1"
num_cpus = "1.17.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tbon = "0.9"
